### ISSUE TITLE
Buffer() is runtime deprecated in Node 10

### ISSUE THREAD

**Issue by nhardy** [fbaiodias/buffer-loader#3]
Calls to `Buffer()` have been deprecated since Node 6, but in Node 10 this is now a runtime deprecation with the message: `[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`. See issue: https://github.com/nodejs/node/issues/19079

It is recommended to instead use the `Buffer.from()` static method documented here: https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_array

Happy to submit a PR.

**Comment by arcanis** [comment]
@fbaiodias Can you release a new version? The one currently in npm still has the issue 😃

**Comment by fbaiodias** [comment]
Published as https://github.com/fbaiodias/buffer-loader/releases/tag/v0.1.0
